### ISSUE TITLE
ipv6 option not honored

### ISSUE THREAD

**Issue by abohmeed** [kubernetes-sigs/ip-masq-agent#53]
The `enable-ipv6 ` feature did not work when added to the config map. When I viewed the container logs, it parsed all the ConfigMap contents except `enable-ipv6`. The only way I could get it to pass IPv6 traffic is to change `cmd/ip-masq-agent/ip-masq-agent.go` line 53 and explicitly set `enable-ipv6` to `true`. This way it becomes the default.

**Comment by varunmar** [comment]
enable-ipv6 is not a config map option, it is a command line option (meaning it does not change for the duration of the daemon's life).
The config map is intended to be changed over the life of the cluster, and the cmdline flags are fixed from the start.

This was a deliberate choice for ipv6 support, since it is not likely that the cluster will gain or lose IPv6 connectivity without major changes to the rest of the cluster anyway.

If you have a use case for changing the IPv6 option during the life of the cluster, I'd be curious to know more. Can you open a feature request describing your use case?
Thanks!

**Comment by abohmeed** [comment]
Hello
I tried setting it through a command-line option and it didn't work. No, we
don't intend to enable/disable IPv6 support while the cluster is running,
we were just looking for a way to enable outbound traffic from the cluster
to the outside world on IPv6. Anyway, Calico says that they have that
option already built-in in their latest version so we'll try that out.
Thank you for getting back to me :)
*Ahmad Al-Fakharany*
*Senior DevOps and Cloud Engineer, Trainer*

**Comment by ganeshr2** [comment]
can u try latest container from gcr and with arg option specified in example below.

        image: gcr.io/google-containers/ip-masq-agent-amd64:v2.5.0
        args:
            - --masq-chain=IP-MASQ
            - --enable-ipv6=true
